//Maya Preference 2018 (Release 1)
//
//
windowPref -topLeftCorner 225 150 -widthHeight 250 400 -maximized false outlinerPanel1Window;
windowPref -topLeftCorner 250 200 -widthHeight 700 400 -maximized false hyperGraphPanel1Window;
windowPref -topLeftCorner 250 200 -widthHeight 660 400 -maximized false graphEditor1Window;
windowPref -topLeftCorner 250 200 -widthHeight 1400 400 -maximized false timeEditorPanel1Window;
windowPref -topLeftCorner 250 200 -widthHeight 660 400 -maximized false dopeSheetPanel1Window;
windowPref -topLeftCorner 250 200 -widthHeight 1040 600 -maximized false nodeEditorPanel1Window;
windowPref -topLeftCorner 250 200 -widthHeight 660 400 -maximized false shapePanel1Window;
windowPref -topLeftCorner 250 200 -widthHeight 1040 600 -maximized false posePanel1Window;
windowPref -topLeftCorner 250 200 -widthHeight 660 400 -maximized false clipEditorPanel1Window;
windowPref -topLeftCorner 250 200 -widthHeight 524 470 -maximized false devicePanel1Window;
windowPref -topLeftCorner 75 75 -widthHeight 1440 900 -maximized false hyperShadePanel1Window;
windowPref -topLeftCorner 250 200 -widthHeight 700 400 -maximized false dynPaintScriptedPanelWindow;
windowPref -topLeftCorner 250 200 -widthHeight 550 562 -maximized false blindDataEditor1Window;
windowPref -topLeftCorner 150 200 -widthHeight 1120 640 -maximized false polyTexturePlacementPanel1Window;
windowPref -topLeftCorner 235 230 -widthHeight 1430 710 -maximized false contentBrowserPanel1Window;
windowPref -topLeftCorner 23 2 -widthHeight 1678 1005 -maximized false MayaWindow;
windowPref -topLeftCorner 364 560 -widthHeight 620 600 -maximized false expressionEditorWin;
windowPref -topLeftCorner 250 946 -widthHeight 546 350 -maximized false OptionBoxWindow;
windowPref -topLeftCorner 364 560 -widthHeight 450 320 -maximized false NewFeatureHighlightWnd;
windowPref -topLeftCorner 210 390 -widthHeight 665 500 -maximized false PreferencesWindow;
windowPref -topLeftCorner 430 688 -widthHeight 244 272 -maximized false bvhImportDialog;
windowPref -topLeftCorner 450 199 -widthHeight 435 344 -maximized false menuSearchWindow;
windowPref -topLeftCorner 375 640 -widthHeight 470 490 -maximized false shelfEditor;
windowPref -topLeftCorner 375 640 -widthHeight 248 75 -maximized false jdsWnd;
windowPref -topLeftCorner 390 640 -widthHeight 520 620 -maximized false connectWindowModal;
windowPref -topLeftCorner 490 1065 -widthHeight 550 411 -maximized false pluginManagerWindow;
windowPref -topLeftCorner 323 1014 -widthHeight 520 620 -maximized false connectWindow;
windowPref -topLeftCorner 298 560 -widthHeight 300 730 -maximized false assignNewMaterialWindow;
windowPref -topLeftCorner 365 560 -widthHeight 600 500 -maximized false cmt_about;
